// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBTU7iFET7S40cVkE0eoGq9xmKY19bWUY',
    appId: '1:134292748113:web:20bbc0a19b8b285b108570',
    messagingSenderId: '134292748113',
    projectId: 'readwiseplus',
    authDomain: 'readwiseplus.firebaseapp.com',
    storageBucket: 'readwiseplus.firebasestorage.app',
    measurementId: 'G-DNG8PRF835',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSUxt7e3ODPhI-xRikXRSLa5AH2zlpuo4',
    appId: '1:134292748113:android:1ca00b6de5ffc002108570',
    messagingSenderId: '134292748113',
    projectId: 'readwiseplus',
    storageBucket: 'readwiseplus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZPo7eR1v4efecCytWleTZ4uMg4jqjJbA',
    appId: '1:134292748113:ios:198fd98aee949043108570',
    messagingSenderId: '134292748113',
    projectId: 'readwiseplus',
    storageBucket: 'readwiseplus.firebasestorage.app',
    iosBundleId: 'com.example.readwisePlus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZPo7eR1v4efecCytWleTZ4uMg4jqjJbA',
    appId: '1:134292748113:ios:198fd98aee949043108570',
    messagingSenderId: '134292748113',
    projectId: 'readwiseplus',
    storageBucket: 'readwiseplus.firebasestorage.app',
    iosBundleId: 'com.example.readwisePlus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBTU7iFET7S40cVkE0eoGq9xmKY19bWUY',
    appId: '1:134292748113:web:8a688358123e0c0b108570',
    messagingSenderId: '134292748113',
    projectId: 'readwiseplus',
    authDomain: 'readwiseplus.firebaseapp.com',
    storageBucket: 'readwiseplus.firebasestorage.app',
    measurementId: 'G-2Q4H3LSW45',
  );
}
